# Generated by Django 4.2.2 on 2025-08-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Vegetable', 'Vegetable'), ('Fruit', 'Fruit'), ('Beverages', 'Beverages')], default='Vegetable', max_length=50),
            preserve_default=False,
        ),
    ]
