# Generated by Django 4.2.2 on 2025-10-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='flat',
            field=models.CharField(default='0', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='Cash', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='pincode',
            field=models.CharField(default='NA', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='street',
            field=models.CharField(default='NA', max_length=100),
            preserve_default=False,
        ),
    ]
