# Generated by Django 6.0.3 on 2026-03-29 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_profile_role_deliverypartner'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='assigned_delivery_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to='myapp.deliverypartner'),
        ),
    ]
