# Generated by Django 6.0.3 on 2026-03-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_backfill_assigned_delivery_partners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Fast Food', 'Fast Food'), ('Desserts', 'Desserts'), ('Beverages', 'Beverages')], default='Fast Food', max_length=50),
        ),
    ]
